### ISSUE TITLE
Adapter bleibt stehen, sobald die Fritze nicht mehr erreichbar ist. 

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064-community#11]
_From @creator81 on December 17, 2017 17:37_

Hallo,
wenn aus irgend einem Grund die Fritzbox mal nicht erreichbar ist, stellt der Adapter seinen Dienst ein. 
Folgendes konnte ich den Logs entnehmen. 

`tr-064.0	2017-12-17 18:05:21.642	error	~
tr-064.0	2017-12-17 18:05:21.642	error	~~ If configuration, networt, IP address, etc. ok, try to restart your FritzBox
tr-064.0	2017-12-17 18:05:21.641	error	~~ Fatal error. Can not connect to your FritzBox.
tr-064.0	2017-12-17 18:05:21.641	error	~
tr-064.0	2017-12-17 18:05:21.639	error	Error: sendSOAPActionRequest Error action=GetInfo serviceType=urn:dslforum-org:service:WLANConfiguration:1: 500 - {'code':500}`

Ich hätte erwartet, dass der Adapter das einfach nach x Sekunden wieder versucht. 

Adapter Version 0.4.10 
Node 6.4

Ich habe aber auch zugegeben alle 10 Sekunden die Fritzbox abgefragt, was wohl etwas übertrieben ist. :) 
Die Fritzbox ist dennoch weiterhin im Netz erreichbar, hat wohl einfach in einem Moment mal nicht geklappt. 

_Copied from original issue: soef/ioBroker.tr-064#53_

**Comment by Apollon77** [comment]
Please retry with Community version here from GitHub
