### ISSUE TITLE
Keinen Anrufernamen mehr

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064-community#12]
_From @pr0j3ctx on January 3, 2018 12:58_

Hallo.

Ich bekomme keinen Anrufernamen mehr angezeigt, obwohl der Kontakt im Telefonbuch hinterlegt ist. Wurde hier irgendetwas geändert? Ich nutze eine 7490 mit aktuellster Firmware.

Gruß
pr0

_Copied from original issue: soef/ioBroker.tr-064#57_

**Comment by jogibear9988** [comment]
_From @soef on January 4, 2018 19:14_

Hallo, kannst Du die LogLevel im Instanzen Tab einmal auf Debug stellen, einen Anruf mit bekanntem Adressbucheintrag anrufen und mit die Log-Ausgaben geben? die Telefonnummern und Namen kannst aus mit xxx überschreiben.

**Comment by jogibear9988** [comment]
_From @legien on January 13, 2018 19:59_

callMonitor.set: type=lastCall caller=xxx callee=xxx callerName=Stefan xxx calleeName=Stefan xxx
callMonitor.set: type=inbound caller=xxx callee=xxx callerName=Stefan xxx calleeName=Stefan xxx

brauchst du noch mehr?

**Comment by jogibear9988** [comment]
_From @pr0j3ctx on January 15, 2018 5:28_

Guten Morgen.

Ich habe im Log-Bereich das Log auf Debug stehen. Im Instanzen TAB kann ich nichts finden zu Debug. Kannst du mir genauer sagen, wo ich dort etwas finde?

Gruß
pr0

**Comment by jogibear9988** [comment]
_From @soef on January 15, 2018 17:59_

Hallo, du musst in der Instanzen-Ansicht oben links den Experten-Modus aktivieren. Dann gibt es in der Mitte eine  Spalte "Log Stufe". Dort sollte für den tr-064 Adapter temporär debug eingestellt werden.

**Comment by jogibear9988** [comment]
_From @pr0j3ctx on February 5, 2018 10:47_

Hallo.
So habe ich es hinbekommen. Sorry für die späte Antwort. Bei mir schaut es so aus.

callMonitor.set: type=lastCall caller=0173xxx callee=xxx
callMonitor.set: type=inbound caller=0173xxx callee=xxx 

callerName und calleeName fehlen bei mir. Ich nutze eine Fritzbox 7490 mit der Firmware 06.93

Woran könnte es liegen?

**Comment by jogibear9988** [comment]
_From @soef on February 13, 2018 16:54_

Kannst Du einmal den kompletten Datenpunkt/Ordner/Device "callmonitor" entfernt und den Adapter einmal neu gestartet? Normal müssten dann alle Datenpunkte angelegt werden.

**Comment by jogibear9988** [comment]
_From @pr0j3ctx on February 16, 2018 7:5_

Seitdem ich das getan habe. Erhalte ich folgende Meldung.

> tr-064.0 | 2018-02-16 08:01:11.287 | error | ~
> -- | -- | -- | --
> tr-064.0 | 2018-02-16 08:01:11.287 | error | ~~ If configuration, networt, IP address, etc. ok, try to restart your FritzBox
>  tr-064.0 | 2018-02-16 08:01:11.287 | error | ~~ Fatal error. Can not connect to your FritzBox.
> tr-064.0 | 2018-02-16 08:01:11.287 | error | ~
> tr-064.0 | 2018-02-16 08:01:11.286 | error | Error: sendSOAPActionRequest Error action=GetInfo serviceType=urn:dslforum-org:service:WLANConfiguration:1: 401 - {"code":401}
> tr-064.0 | 2018-02-16 08:01:10.907 | info | starting. Version 0.4.14 in /opt/iobroker/node_modules/iobroker.tr-064, node: v4.8.7

´Mir ist unklar, wo der send SOAP herkommt. Ebenso warum die Box nicht mehr erreichbar ist. Der Fritzbox Adapter funktioniert und über 4900 kann ich mir auch die xml`s abrufen.

Ich habe den Adapter gelöscht und neu installiert, aber den Request hat er immer noch im Bauch. "sendSOAPActionRequest Error action=GetInfo serviceType=urn:dslforum-org:service:WLANConfiguration:1: 401 - {"code":401}"

**Comment by jogibear9988** [comment]
_From @soef on February 17, 2018 14:44_

Hallo, Code 401 ist ja "unauthorized". Bist du sicher, den richtigen Usernamen und Passwort eingetragen zu haben?

**Comment by jogibear9988** [comment]
_From @pr0j3ctx on February 19, 2018 13:16_

Ja, das ist definitiv richtig.
Ich nutze im Heimnetz keinen Benutzernamen und lasse ihn daher auch leer in der Instanz. So hat es bis dahin auch funktioniert.

Kann ich den Adapter einmal restlos löschen? Gibt es hierfür spezielle Befehle?

**Comment by jogibear9988** [comment]
_From @soef on February 19, 2018 18:31_

Leg' doch einmal einen Benutzer in der FritzBox (System -> FRITZ!Box-Benutzer) an und verwende den Benutzernamen (mit dem für ihn vergebenem Password). Vielleicht hat AVM da etwas geändert.

Die Instanz(en) kannst Du im ioBroker Admin unter "Instanzen" entfernen. Den kompletten Adapter inklusive Code kannst du im ioBroker Admin unter "Adapter" entfernen und wieder neu installieren.

**Comment by jogibear9988** [comment]
_From @pr0j3ctx on February 28, 2018 9:43_

Nachdem ich nun die Authentifizierung umgestellt habe auf Benutzer und Passwort klappt es. Seltsamerweise hat es vorher ja auch anders funktioniert.
Da ich wegen anderer Umstände auf die Authentifizierung im Heimnetzwerk nur mit Passwort angewiesen bin, wäre es super wenn man dies hier fixen könnte.

**Comment by guergen1** [comment]
Hallo, manchmal bekomme ich den Namen in die Caller in die Objekte unter Caller und CallerName angezeigt, manchmal nicht...
![grafik](https://user-images.githubusercontent.com/34395245/66256694-d799d280-e790-11e9-8204-9dbd086a184c.png)

**Comment by Apollon77** [comment]
Daten werden nur aktualisiert wenn sie sich ändern. EIin anderes Issue beleuchtet noch den Fall von "unterdrückter nummer".
