### ISSUE TITLE
Device wird als abwesend erkannt

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064-community#2]
_From @derAndyk on February 12, 2019 8:0_

Hallo,  ich habe das Problem, dass besonders Nachts die Handys mehrfach als An und Abwesend gemeldet werden. ich habe eine Fritzbox 7590 und 3 Fritz Repeater (im Mesh Betrieb) laufen. 
Das Handy Bsp. iPhone 6s liegt die Nacht über an der selben stelle (voller WLAN Empfang), es ändert jedoch bis zu 30 mal zwischen 23 und 5 Uhr den Status Aktiv / inaktiv.

Ich hab den Pool Intervall auf 60 Sekunden gestellt. 

_Copied from original issue: soef/ioBroker.tr-064#90_

**Comment by Apollon77** [comment]
Dann bitte passend den Status in der Fritzbox prüfen (ich weiss das das Nachts blöd ist), aber an sich funktioniert die Logik vom Adapter und nutzt nur Daten der Fritzbox. Gibt es Fehler logs in der Zeit?
