### ISSUE TITLE
forEachConfiguredDevice: in GetSpecificHostEntry 4(/xx:xx:A8:xx:4A):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064-community#23]
_From @Michaelnorge on August 14, 2018 17:21_

I have a problem with tr-064 together with ioBroker and FRITZ!Box 7430.

I started using it a while ago and it did its job,
But now since I started to control the guest-network (online/offline-control) ioBroker shows that error all over:forEachConfiguredDevice: in GetSpecificHostEntry 4(/xx:xx:A8:xx:4A):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500} - after getting this error tr-064 is not updating anymore on guest network.

I searched on Google and found a lot of people with the same problem.

So my suggestion is that it will be enough for me to see if somebody IS online on guest network or NOT.
So like true (1) or false (0).

It will be wunderfull if that is shown at the objects of ioBroker.

Is it maybe possible to change that??

Greetings fm Norway/Germany

Michael

_Copied from original issue: soef/ioBroker.tr-064#76_

**Comment by jogibear9988** [comment]
_From @daniel-lo on September 25, 2018 15:38_

It also happend to me .. 

forEachConfiguredDevice: in GetSpecificHostEntry 0(sonoff-garage/xx:xx:94:A1:xx:89):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - 

I did nothing to the adapter .. what can I do?

**Comment by jogibear9988** [comment]
_From @timae146 on October 15, 2018 14:49_

Same here. Is it, because the device is in guest-wlan? is it fixable? 

![tr64](https://user-images.githubusercontent.com/42387818/46958496-3ce54700-d09a-11e8-9879-6fcc3a375d65.PNG)

**Comment by jogibear9988** [comment]
_From @daniel-lo on October 29, 2018 5:20_

BTW .. mine was not a Guest-Wifi thing .. but maybe a repeater thing.

**Comment by jogibear9988** [comment]
_From @vr6syncro on December 6, 2018 14:4_

i have this issue too since few hours,

**Comment by jogibear9988** [comment]
_From @Leviathan09 on February 3, 2019 13:34_

Same problem here getting the following error sometimes:
`tr-064.0	2019-02-03 08:05:07.627	error	forEachConfiguredDevice: in GetSpecificHostEntry 0(Galaxy-S8-Tobi/30:07:4D:0C:62:D7):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: - {"`

As @daniel-lo is suggesting, could it be a repeater thing?
I have the fritz repeater 1750e and a fritz box 7590 running with the latest official firmware.

**Comment by jogibear9988** [comment]
_From @serex81 on February 11, 2019 22:16_

I have the same Problem but only with my Phone, my girlfriends phone is working.
`Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500`

**Comment by Supermicha81** [comment]
I just wanted to open a new bug report but I found this issue.
I have the same error
`error: tr-064-community.0 (1123) forEachConfiguredDevice: in GetSpecificHostEntry 34(Nettis-Lappi/9C:B7:0D:BC:EA:BA):Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}`

I use this device not frequently, after maybee a week or two and if I restart the FritzBox, this error appears.
I think this is may be connected with the DHCP-Lease-Time.
When this problem occures the FritzBox seems to have forgotten the device.
In this case, the request of the adapter must run into an error... so it seems not to be a problem of the adapter but maybee the handling for unknown devices could be changed?

(If I connect the specific device again to my network, the FritzBox just remember and the error is gone...)

**Comment by Ilovegym66** [comment]
very good investigation! on my site the same effect, and I confirm the lease time effect!

**Comment by Apollon77** [comment]
The question is how to change it ... how the adapter should detect misconfiguration vs "device forgotten"? And what we should log how?

**Comment by Hans-Zwiesel** [comment]
my suggestion:
Please make this error to warn, so we can it fade out from the log

**Comment by Apollon77** [comment]
ok, changed to warn

**Comment by Hans-Zwiesel** [comment]
many thanks.
where can i install this change?
when i update the adapter, i get this error "Fertig mit Fehler: host.raspi4 Cannot install iobroker.tr-064@0.4.18: 243"

**Comment by Apollon77** [comment]
Der neue Adapter ist "Neu". Also per Custom Install im Admin via https://github.com/iobroker-community-adapters/ioBroker.tr-064-community installieren, instanz anlegen, Konfig umziehen, alte löschen wenn alles tut

**Comment by Hans-Zwiesel** [comment]
Vielen Dank.
Habe ich gemacht, Community Adapter läuft jetzt.
Die Fehler Unterdrückung muß ich erst noch testen.
