### ISSUE TITLE
Suche mit Namen im Telefonbuch funktioniert nicht

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064-community#27]
_From @Marty56 on October 2, 2018 6:9_

Ich habe versucht mit tr-064.0.phonebook.name im Telefonbuch nach der Nummer zu suchen.
Die umgekehrte Suche, Tel -> Name funktioniert.

_Copied from original issue: soef/ioBroker.tr-064#80_

**Comment by Apollon77** [comment]
@Marty56 Please check 2.0 from GitHub. Needs js-controller 2.0!
