### ISSUE TITLE
Geräte suchen ohne Funktion

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064-community#28]
_From @Nyrk2k on October 7, 2018 18:9_

Fritz OS 7.0

GetHostNumberOfEntries:Error

Version 0.4.18 anders 0.4.14 tested.

_Copied from original issue: soef/ioBroker.tr-064#81_

**Comment by thunder1504** [comment]
Hey zusammen, gibt es hier schon irgendwelche Info´s zu ? 
Habe so ziemlich das selbe Problem und bin schon mehrere Tage dran das Problem zu lösen.... vergebens...... mein LOG:


tr-064.0 | 2019-05-16 17:20:32.054 | error | ~~ If configuration, networt, IP address, etc. ok, try to restart your FritzBox
-- | -- | -- | --
tr-064.0 | 2019-05-16 17:20:32.054 | error | ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2019-05-16 17:20:32.053 | error | ~
tr-064.0 | 2019-05-16 17:20:32.048 | error | Error: read ECONNRESET - {"errno":"ECONNRESET","code":"ECONNRESET","syscall":"read"}
tr-064.0 | 2019-05-16 17:17:51.786 | error | GetHostNumberOfEntries:Error: hosts.actions.GetHostNumberOfEntries is not a function - {}

**Comment by Apollon77** [comment]
ECONNRESET heisst das die Friotzbox die Verbindung beendet hat. Bitte nochmals versuchen (vllt mit aktuellster GitHub Version von hier), sonst mal die "Last" auf der Fritzbox prüfen und die Einstellungen

**Comment by Apollon77** [comment]
Bitte ggf neues Issue öffnen. Gerätesuche tut bei mir
