### ISSUE TITLE
Cannot connect to FB after upgrading 7490 to 07.28

### ISSUE THREAD

**Issue by EvilEls** [iobroker-community-adapters/ioBroker.tr-064-community#303]
I upgraded my 7490 to 07.28.
Upon instance start I get:

<html><body>

tr-064.0 | 2021-10-18 16:13:53.124 | warn | Terminated (JS_CONTROLLER_STOPPED): Fatal error. Can not connect to your FritzBox.
-- | -- | -- | --
tr-064.0 | 2021-10-18 16:13:53.123 | error | ~
tr-064.0 | 2021-10-18 16:13:53.123 | error | ~~ If configuration, network, IP address, etc. ok, try to restart your FritzBox
tr-064.0 | 2021-10-18 16:13:53.123 | error | ~~ Fatal error. Can not connect to your FritzBox.
tr-064.0 | 2021-10-18 16:13:53.122 | error | ~
tr-064.0 | 2021-10-18 16:13:53.122 | error | Error: sendSOAPActionRequest Error action=GetInfo serviceType=urn:dslforum-org:service:WLANConfiguration:1: 500 - {"code":500}
tr-064.0 | 2021-10-18 16:13:52.468 | info | starting. Version **4.2.14** in /opt/iobroker/node_modules/iobroker.tr-064, node: v**12.22.6**, js-controller: **3.3.18**

</body>
</html>

I removed all monitored devices
disabled all features in settings
removed ip, user, pass in settings, saved and set them again
restarted FB

**Comment by Apollon77** [comment]
No idea ... you can try to create an other new user with a new name ... else I can only say "restart Fritzbox" ...
