### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by mistermaster2punkt0** [iobroker-community-adapters/ioBroker.tr-064-community#37]
Seit kurzem darf auch ich nun eine Fritzbox mein Eigen nennen. Nun würde ich gerne diesen Adapter in Betrieb nehmen. Ich habe die aktuelle Version des Adapters installiert. Leider startet er nicht. Im Log steht:
host.ioBroker-RasPi | 2019-03-31 22:59:14.141 | error | startInstance tr-064-community.0: cannot find start file!

Einen Upload habe ich bereits durchgeführt. 
Woran könnte es liegen, dass er nicht starten will?

**Comment by Apollon77** [comment]
Wir übernehmen die Adapter gerade erst ... Dauert ggf noch ein paar Tage. Aöternativ die alte Verion von "soef" bzw die aus dem repo nehmen

**Comment by mistermaster2punkt0** [comment]
Oh, okay. Alles klar :-)
Die von soef startet bei mir zwar, geht jedoch nach 2 Sekunden sofort auf rot ...
Dann muss ich wohl noch ein bisschen warten. Vielen Dank für die schnelle Nachricht!

**Comment by libertyx82** [comment]
Die alte Version startet bei mir leider auch nicht mehr.


```
host.IoBroker | 2019-05-07 16:19:12.110 | error | instance system.adapter.tr-064.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: at bootstrap_node.js:625:3
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: at startup (bootstrap_node.js:204:16)
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: at Function.Module.runMain (module.js:694:10)
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: at Function.Module._load (module.js:498:3)
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: at tryModuleLoad (module.js:506:12)
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: at Module.load (module.js:566:32)
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: at Object.Module._extensions..js (module.js:664:10)
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: at Module._compile (module.js:653:30)
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:16:20)
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: TypeError: fns.adapter is not a function
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: ^
Caught | 2019-05-07 16:19:12.110 | error | by controller[0]: fns.adapter = fns.adapter(options);
Caught | 2019-05-07 16:19:12.109 | error | by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1383
```

**Comment by slimline33** [comment]
Habe heute den Admin Adapter geupdatet und seitdem auch das Problem wie @libertyx82 . Adapter gelöscht, Instanz gelöscht. Neuestes Paket via Github hinzugefügt und habe jetzt nur noch:

host.iobroker666 | 2019-05-18 18:08:02.899 | error | startInstance tr-064-community.0: cannot find start file!

Admin Version: 3.6.2
FritzOS:  07.08-68239 BETA

Bekomme leider keine anderen Fehlermeldungen - trotz Debug Modus.

Gruß slimline

**Comment by Apollon77** [comment]
mach mal 

iobroker upload tr-064

**Comment by slimline33** [comment]
`
root@iobroker666:/opt/iobroker# iobroker upload tr-064                                                                                        
Cannot find io-package.json in null                                                                                                           
Cannot parse null/io-package.json:Error: ENOENT: no such file or directory, open 'null/io-package.json'
`

Habe jetzt aber auch gesehen, dass ich den TR-64 Adapter zweimal in der Liste der Instanzen habe. Sehe aber dass es eine Community Edition gibt und den normalen? Die haben natürlich unterschiedliche Ordner. Die Fehlermeldung **cannot find start file!** kommt bei dieser.

Nehme ich die Version aus der Instanzenliste bekomme ich obige Fehler

`

host.iobroker666 | 2019-05-19 12:14:42.797 | error | instance system.adapter.tr-064.0 terminated with code 1 ()
-- | -- | -- | --
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: at bootstrap_node.js:625:3
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: at startup (bootstrap_node.js:204:16)
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: at Function.Module.runMain (module.js:694:10)
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: at Function.Module._load (module.js:498:3)
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: at tryModuleLoad (module.js:506:12)
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: at Module.load (module.js:566:32)
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: at Object.Module._extensions..js (module.js:664:10)
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: at Module._compile (module.js:653:30)
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:16:20)
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: TypeError: fns.adapter is not a function
Caught | 2019-05-19 12:14:42.797 | error | by controller[0]: ^
Caught | 2019-05-19 12:14:42.796 | error | by controller[0]: fns.adapter = fns.adapter(options);
Caught | 2019-05-19 12:14:42.796 | error | by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1383

`

**Comment by libertyx82** [comment]
Die Version 0.4.14 aus dem repro fuktioniert bei mir.

**Comment by slimline33** [comment]
Die nutze ich jetzt auch und funktioniert ebenso.

**Comment by Apollon77** [comment]
Bitte aktuelle Version von Hier per GitHub installieren
