### ISSUE TITLE
Kein Start nach Update vom JS Controller auf 1.5.7

### ISSUE THREAD

**Issue by actionbyte** [iobroker-community-adapters/ioBroker.tr-064-community#40]
Habe gestern iobroker und JS Controller auf neueste Version geupdatet.
Nach dem Update vom JS auf 1.5.7 startet der AVM Adapter nicht mehr. Letzte Zeile im Log lautet:

nstance system.adapter.tr-064.0 terminated with code 1 ()

**Comment by Apollon77** [comment]
AM besten mal manuell von der Kommandozeile starten. Dann kommen ggf mehr logs.

ins ioBroker Verzeichnis wechseln, dann dort
node node_modules/iobroker.tr-064/tr-064.js --force --logs

Was ist dann die Ausgabe?

PS: Am besten gleich die 1.5.8 vom js-controller nehmen :-)

**Comment by Monox83** [comment]
Hi, ich hab nen Update auf 1.5.8 gemacht und es startet bei mir auch nicht mehr..
Hier mal das Log.
`root@iobroker:/opt/iobroker# node node_modules/iobroker.tr-064/tr-064.js --force --logs
{"code":"MODULE_NOT_FOUND"}
{"code":"MODULE_NOT_FOUND"}
{"code":"MODULE_NOT_FOUND"}
/opt/iobroker/node_modules/soef/soef.js:1383
    fns.adapter = fns.adapter(options);
                      ^

TypeError: fns.adapter is not a function
    at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:16:20)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)`

**Comment by actionbyte** [comment]
Ich habe nun den Communty Adapter vom Github installiert, und gleichzeitig auch den JS Controller 2.0 (von gestern)?
Jetzt funktioniert weder der tr964 noch mein Alexa 2 Adapter. ;-(

> pi@raspberrypi:/opt/iobroker $ node node_modules/iobroker.tr-064/tr-064.js --for                    ce --logs
{"code":"MODULE_NOT_FOUND"}
{"code":"MODULE_NOT_FOUND"}
{"code":"MODULE_NOT_FOUND"}
/opt/iobroker/node_modules/soef/soef.js:1383
    fns.adapter = fns.adapter(options);
                      ^

TypeError: fns.adapter is not a function
    at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:                    16:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
pi@raspberrypi:/opt/iobroker $ pi@raspberrypi:/opt/iobroker $ node node_modules/                    iobroker.tr-064/tr-064.js --force --logs
-bash: pi@raspberrypi:/opt/iobroker: Datei oder Verzeichnis nicht gefunden
pi@raspberrypi:/opt/iobroker $ {"code":"MODULE_NOT_FOUND"}
-bash: {code:MODULE_NOT_FOUND}: Kommando nicht gefunden.
pi@raspberrypi:/opt/iobroker $ {"code":"MODULE_NOT_FOUND"}
-bash: {code:MODULE_NOT_FOUND}: Kommando nicht gefunden.
pi@raspberrypi:/opt/iobroker $ {"code":"MODULE_NOT_FOUND"}
-bash: {code:MODULE_NOT_FOUND}: Kommando nicht gefunden.
pi@raspberrypi:/opt/iobroker $ /opt/iobroker/node_modules/soef/soef.js:1383
-bash: /opt/iobroker/node_modules/soef/soef.js:1383: Datei oder Verzeichnis nich                    t gefunden
pi@raspberrypi:/opt/iobroker $     fns.adapter = fns.adapter(options);
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi:/opt/iobroker $                       ^
-bash: ^: Kommando nicht gefunden.
pi@raspberrypi:/opt/iobroker $
pi@raspberrypi:/opt/iobroker $ TypeError: fns.adapter is not a function
-bash: TypeError:: Kommando nicht gefunden.
pi@raspberrypi:/opt/iobroker $     at Object.exports.Adapter (/opt/iobroker/node                    _modules/soef/soef.js:1383:23)
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi:/opt/iobroker $     at Object.<anonymous> (/opt/iobroker/node_mod                    ules/iobroker.tr-064/tr-064.js:16:20)
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi:/opt/iobroker $     at Module._compile (module.js:653:30)
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi:/opt/iobroker $     at Object.Module._extensions..js (module.js:6                    64:10)
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi:/opt/iobroker $     at Module.load (module.js:566:32)
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi:/opt/iobroker $     at tryModuleLoad (module.js:506:12)
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi:/opt/iobroker $     at Function.Module._load (module.js:498:3)
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi:/opt/iobroker $     at Function.Module.runMain (module.js:694:10)                    -bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi:/opt/iobroker $     at startup (bootstrap_node.js:204:16)
-bash: Syntaxfehler beim unerwarteten Wort `('
pi@raspberrypi:/opt/iobroker $     at bootstrap_node.js:625:3
-bash: at: Kommando nicht gefunden.
pi@raspberrypi:/opt/iobroker $ pi@raspberrypi:/opt/iobroker $
-bash: pi@raspberrypi:/opt/iobroker: Datei oder Verzeichnis nicht gefunden
pi@raspberrypi:/opt/iobroker $

**Comment by actionbyte** [comment]
Habe gestern Raspian komplett neu installiert und Backup vom iobroker wieder restored. 
Läuft soweit alles ausser der tr-064. Im Log steht nur:

host.raspberrypi | 2019-05-09 06:11:20.439 | error | startInstance tr-064-community.0: cannot find start file!
-- | -- | -- | --

Ich habe den Adapter der Coumminty aus dem Github hier installiert, beim Start über Komandozeile dennoch erscheint das hier:

pi@raspberrypi:/opt $ cd /opt/iobroker
pi@raspberrypi:/opt/iobroker $ node node_modules/iobroker.tr-064/tr-064.js --force --logs
{"code":"MODULE_NOT_FOUND"}
{"code":"MODULE_NOT_FOUND"}
{"code":"MODULE_NOT_FOUND"}
/opt/iobroker/node_modules/soef/soef.js:1383
    fns.adapter = fns.adapter(options);
                      ^

TypeError: fns.adapter is not a function
    at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:16:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
pi@raspberrypi:/opt/iobroker $

**Comment by daniel-lo** [comment]
läuft net :-(

**Comment by Apollon77** [comment]
Einigender hatten Erfolg mit einem 

npm install soef

**Comment by daniel-lo** [comment]
hab ich auch schon probiert .. ist für mich grad nicht so sehr wichtig .. ich wart halt noch ein paar Tag. Find's aber super, dass ihr den Adapter weiter pflegen wollt. Vielen Dank!

`root@ioBroker:~# npm install soef
/root
`-- soef@0.1.49
  +-- array-ext@0.1.5
  `-- sprintf-js@1.1.2

npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
root@ioBroker:~# sudo npm install soef
/root
`-- soef@0.1.49

npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.
`

**Comment by Monox83** [comment]
Moin,
npm install soef
hat bei mir unter Debian funktioniert.

Vielen Dank

Monox

**Comment by daniel-lo** [comment]
Krieg ich den alten Adapter aus der Adapterliste raus?

**Comment by Apollon77** [comment]
Sobald der neue offizeil im Repository ist klappt das :-) Aktuell ist da nich der "alte" drin

**Comment by actionbyte** [comment]
@daniel-lo : Bei mir das gleiche Ergebnis. Funktioniert ebenfalls **nicht** mit
npm install soef

**Comment by dontobi** [comment]
Ich habe das selbe Problem. Habe auf die GitHub Version geupdated und auch npm Install soef durchgeführt. Beides klappt nicht. Im Moment läuft bei mir der js-controller in Version 1.5.8.

**Comment by actionbyte** [comment]
js-controller V 1.5.8 mit tr-064-community:

pi@raspberrypi:/opt/iobroker $ node node_modules/iobroker.tr-064-community/tr-064.js --force --logs
{"code":"MODULE_NOT_FOUND"}
{"code":"MODULE_NOT_FOUND"}
{"code":"MODULE_NOT_FOUND"}
/opt/iobroker/node_modules/soef/soef.js:1383
    fns.adapter = fns.adapter(options);
                      ^

TypeError: fns.adapter is not a function
    at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
    at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064-community/tr-064.js:16:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
pi@raspberrypi:/opt/iobroker $

**Comment by actionbyte** [comment]
Mit der JS-Controller Version 1.5.9 hat sich leider nichts geändert... er läuft auch hier nicht.

**Comment by actionbyte** [comment]
Das Glück ist mit die Dummen!
Ich habe es hinbekommen, für alle die hier noch die gleichen Probleme haben wie ich sie hatte:

Installiert war der Community Adapter bei mir, alleine weil auf der soef Seite ja stand das der von soef nicht weiter entwickelt wird und man den tr064-community nehmen solle.
Dieser ist mit o.g. Problemen bei mir nicht zum Laufen zu bekommen.

Ich habe nun aus der Repository den soef tr-064 wieder installiert, nach der Installation wurde die Konfigurationsseite nicht geöffnet, startindex würde fehlen.
Danach habe ich den Adapter sofort wieder deinstalliert und nur nochmals wieder installiert. Mit dem halben Erfolg das nun die Einrichtungsseite erschien und ich die Verbindungsdaten zur Fritz.Box eingeben konnte. Nur leider wieder mit dem gleichen Misserfolg das dieser nicht startete und im Log als letzte Zeile diese erschien: 
error | instance system.adapter.tr-064.0 terminated with code 1 ()

Nun über SSH:
cd /op/iobroker
cd node_modules
cd iobroker.tr-064
sudo npm install soef

Log hiervon:
pi@raspberrypi:/opt/iobroker $ cd node_modules
pi@raspberrypi:/opt/iobroker/node_modules $ cd iobroker.tr-064
pi@raspberrypi:/opt/iobroker/node_modules/iobroker.tr-064 $ sudo npm install soef
npm WARN deprecated dgram@1.0.1: npm is holding this package for security reasons. As it's a core Node module, we will not transfer it over to other users. You may safely remove the package from your dependencies.
npm notice created a lockfile as package-lock.json. You should commit this file.
+ soef@0.4.15
added 7 packages from 5 contributors and audited 10 packages in 3.258s
found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
pi@raspberrypi:/opt/iobroker/node_modules/iobroker.tr-064 $

Nun übers WebIf den Adapter gestartet .... und er läuft wieder!

Vielleicht hilft mein Vorgehen ja dem ein oder anderen....

**Comment by daniel-lo** [comment]
Weiß nicht ob ich mich mit dem "nicht-community" nochmal beschäftigen möchte.  @Apollon77 kannst Du einen Tipp geben ob ich das lieber tun sollte? Bitte nicht Drängeln verstehen .. nur ein dauert oder stehen kurz davor :-)

**Comment by Apollon77** [comment]
Bitte aktuelle GutHib Version von hier installieren.
