### ISSUE TITLE
Datenpunkt ringring doppelt und Fehler

### ISSUE THREAD

**Issue by sigi2345** [iobroker-community-adapters/ioBroker.tr-064-community#45]
Hallo,

der DP ringring ist doppelt, wobei einer reagiert und der 2. nicht.

![Screenshot (3325)_LI](https://user-images.githubusercontent.com/41079106/58543395-b2ec8780-81ff-11e9-99a3-2f2e2b114dfb.jpg)

**Comment by Apollon77** [comment]
welcher von beiden tut denn und welcher nicht? :-) Der auf "true" tut?

**Comment by sigi2345** [comment]
> welcher von beiden tut denn und welcher nicht? :-) Der auf "true" tut?

Ja.....

**Comment by SBorg2014** [comment]
Der "liegt" aber auch falsch: callmonitor.**callmonitor**.ringing
Richtig wäre: callmonitor.ringing

**Comment by sigi2345** [comment]
Neu installiert , Problem besteht immer noch........

**Comment by sigi2345** [comment]
> Der "liegt" aber auch falsch: callmonitor.**callmonitor**.ringing
> Richtig wäre: callmonitor.ringing

Das kommt automatisch..........

**Comment by Apollon77** [comment]
fixed by https://github.com/iobroker-community-adapters/ioBroker.tr-064-community/commit/da5b439859940959dde4bf0849fb50470ed5e0c2
