### ISSUE TITLE
Fehlercode 243 bei Installation

### ISSUE THREAD

**Issue by actionbyte** [iobroker-community-adapters/ioBroker.tr-064-community#46]
Habe den alten TR064 von Soef  gestoppt und den alten Adapter der Community deinstalliert.
Danach über die URL die aktielle Github Version installiert, dabei trat Fehler 243 im Lg auf und Instanz bzw. Adapter ist nicht vorhanden:

$ ./iobroker url "https://github.com/iobroker-community-adapters/ioBroker.tr-064-community"
install https://github.com/iobroker-community-adapters/ioBroker.tr-064-community/tarball/master
npm install https://github.com/iobroker-community-adapters/ioBroker.tr-064-community/tarball/master --production --save --prefix "/opt/iobroker" (System call)
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/array-extnpm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/dgram
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/ip
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/safe-buffer
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/dns-packet
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/sprintf-js
npm WARN checkPermissions Missing write access to /opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/soef

npm
 WARN
 bl@0.7.0 requires a peer of stream-browserify@* but none is installed. You must install peer dependencies yourself.

npm
 ERR!
 path
 /opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/array-extnpm
 ERR! 
code EACCESnpm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/array-ext'npm ERR!  { Error: EACCES: permission denied, access '/opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/array-ext'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/array-ext\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/opt/iobroker/node_modules/iobroker.tr-064-community/node_modules/array-ext' }

npm ERR! npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running

npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-05-31T07_29_39_417Z-debug.log

ERROR: host.raspberrypi Cannot install https://github.com/iobroker-community-adapters/ioBroker.tr-064-community/tarball/master: 243
ERROR: process exited with code 25

**Comment by Apollon77** [comment]
Permission denied ... please Check file System rights. Ideally use the installation Fixer script (see forum). No problem of this particular adapter.
