### ISSUE TITLE
Feature-Requests: DP CallerName unter callmonitor nach Anruf löschen

### ISSUE THREAD

**Issue by ihavenonick** [iobroker-community-adapters/ioBroker.tr-064-community#49]
Wenn der DP nicht gelöscht wird, wird der vorherige Name bei einem Ansage Script wiedergegeben.

**Comment by Apollon77** [comment]
Details bitte? Bzw bitte neu versuchen mit neuer GitHub Verison heute abend

**Comment by ihavenonick** [comment]
Werds mal testen, wobei ich den DP jetzt eh nach einem Anruf und der erfolgten Ansage gleich lösche.

**Comment by Apollon77** [comment]
Und dieses „löschen am Adapter vorbei“ hat übrigens den Nebeneffekt das wenn der gleiche Anrufer wie davon anruft die Felder nicht neu geschrieben werden.

Also die Frage ist was genau das Problem ist? Sind es Anrufer ohne Nummer die dann falsch angesagt werden oder wie? 
Weiterhin Weinländer die ansagelogik? Wie wird erkannt ob ein Anruf stattfindet? Timestamp ändert sich? Wenn ja dann werden ggf danach die anderen States gelesen? Das kann aus Riming Gründen in jedem Fall zu falschen Ansagen führen. 
Am besten den json State nutzen und alle Daten dort auslesen.

**Comment by ihavenonick** [comment]
So, ich habe mal mein lösch Script deaktiviert und läuft bestens. Da bei einem unbekannten Anruf kein Name unter callerName steht sagt mein Script auch nichts an und wenn 2 mal hintereinander der selbe anruft, wird er auch jedes mal angesagt.
Für mich passt so alles.
