### ISSUE TITLE
Error code 156 bei geplantem Restart des Adapters

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064-community#5]
_From @buanet on July 11, 2017 21:19_

Hallo, ich starte den Adapter über ioBroker regelmäßig neu.
Bei den dadurch ausgelösten Neustarts habe ich allerdings jedes mal einen Fehler mit Code 156 im Log:

tr-064.0 | 2017-07-11 23:01:03.039 | info | starting. Version 0.3.19 in /opt/iobroker/node_modules/iobroker.tr-064, node: v6.10.3
-- | -- | -- | --
host.nas | 2017-07-11 23:01:01.587 | info | instance system.adapter.tr-064.0 started with pid 29059
host.nas | 2017-07-11 23:01:00.067 | info | Restart adapter system.adapter.tr-064.0 because enabled
host.nas | 2017-07-11 23:01:00.067 | error | instance system.adapter.tr-064.0 terminated with code 156 ()
tr-064.0 | 2017-07-11 23:01:00.048 | info | terminating
tr-064.0 | 2017-07-11 23:01:00.036 | info | Scheduled restart.

Die Funktion ist dadurch aber offensichtlich nicht eingeschränkt.

MfG,
André

_Copied from original issue: soef/ioBroker.tr-064#35_

**Comment by Apollon77** [comment]
these are normal logs from js-controller
