### ISSUE TITLE
FritzBox Gastnetz Fehlermeldung

### ISSUE THREAD

**Issue by Hans-Zwiesel** [iobroker-community-adapters/ioBroker.tr-064-community#51]
(In der Soef Version:)
Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 500 - {"code":500}

und zwar NUR von den Geräten, die im Gäste-Wlan der FritzBox 7560 NICHT mehr angemeldet sind.
Sind diese Geräte wieder angemeldet, dann keine Fehlermeldung.
Von Geräten im "normalen" Netzwerk erfolgt keine Fehlermeldung.

Wäre super, wenn Ihr bei der Überarbeitung diesen Fehler fixen würdet.

**Comment by umbm** [comment]
Bei mir die gleiche Fehlermeldung (tr-064-community-adapter), seit ich ein Gerät im Fritz7490-Gastnetz überwachen lasse.
Error: sendSOAPActionRequest Error action=GetSpecificHostEntry serviceType=urn:dslforum-org:service:Hosts:1: 50

**Comment by Apollon77** [comment]
duplicate #23
