### ISSUE TITLE
Tr-064 lässt sich nur für jeweils 5 Sekunden starten

### ISSUE THREAD

**Issue by PatrickFro** [iobroker-community-adapters/ioBroker.tr-064-community#53]
Der Adapter lässt sich jeweils nur ca. 5 Sekunden starten, dann wechselt die Farbe von Grün auf Rot und im Log erscheint folgendes: 
![TR064](https://user-images.githubusercontent.com/52123261/59973244-52056480-959d-11e9-91c5-0f4db43858f3.PNG)

Bereits versucht:
-Anderen FritzBox-User nutzen (keine Änderung)
-FritzBox Neustart (keine Änderung)
- Upnp Einstellung Fritzbox geprüft
-IoBroker Neustart (keine Änderung)
-ioBroker Installation "Fixer" (keine Änderung)
-Ping Fritzbox - (keine Änderung aber erfolgreich)
-Alten Soef-Adapter installiert,  cd /opt/iobroker/
   iobroker stop tr-064
   cd /opt/iobroker/node_modules/iobroker.tr-064
   npm install soef
durchgeführt (keine Änderung)

**Comment by actionbyte** [comment]
Schaut so aus als ob der Adapter die Box erst gar nicht findet. Nutzt du die IP oder den Hostnamen der Box?

**Comment by PatrickFro** [comment]
Zuerst fritz.box, nun auch mal die IP, leider keine Änderung.

**Comment by PatrickFro** [comment]
So, ich habe es geschafft! Grund meiner Probleme war, dass ich die Anrufliste in der FritzBox deaktiviert hatte (kein angeschlossenes Telefon, kein Bedarf) . Zwar habe ich im Adapter auch alles mit Telefon abgewählt, Fehler erschien trotzdem.

**Comment by epcos71** [comment]
Das Problem besteht bei mir weiterhin, trotz aller oben genannten Einstellungen. Zusätzlich werden auch keine Eigenschaften des Objekts, sondern nur der Objektname angezeigt.

**Comment by Apollon77** [comment]
Bitte community Version installieren und checken
