### ISSUE TITLE
iOS: state devices.xxx.active changes false/true/false if person leaves

### ISSUE THREAD

**Issue by Mic-M** [iobroker-community-adapters/ioBroker.tr-064-community#55]
**Describe the bug**  
Using iOS devices (iPhone, and iPad), I noticed a weird behavior:
Once the device is no longer in WiFi, the adapter changes the state 'tr-064-community.0.devices.XXX.active' to false either
 1. after about 10 minutes,
 2. or within a few seconds

It looks like this is random, so sometimes option 1 is happening, and sometimes option 2.

In the second case (so if within a few seconds), it changes community.0.devices.XXX.active' to true after about 15 seconds again, and then finally to false after about 10 minutes.
So: 
Person is leaving:  after few seconds: active=false, after 15 seconds active=true, after 10min active=false

**To Reproduce**  
See above. Looks almost like a Fritzbox issue, but I thought I report it. I have coded a workaround for a presence script, see [here at Github](https://github.com/Mic-M/iobroker.presence-script-for-tr-064-community-adapter/blob/master/presence-script-for-tr-064-community-adapter.js), see option FIX_ERROR in the script.

**Expected behavior**  
Expected is that it does not change the active state back and forth to false and true.

**Versions:**  
 - Adapter version: 1.00
 - JS-Controller version: 1.5.12
 - Node version: 8.16
 - Operating system: Debian

P.S. many thanks for the new text template to report issues :-)

**Comment by Apollon77** [comment]
The Adapter is accessing the FritzBox and exactly shows what's there. So please try to verify what you could see in Fritzox UI ... it should be the same.
I have no idea what we could do against that :-(

**Comment by actionbyte** [comment]
@Mic-M:

Do you have other Mesh-APs?
I could observe similar behavior and think that the main box, where you ask the presence, recognizes the absence. The participant is then really nowhere in the network more available. But then another access point logs them in the box again because he has listed the participant as a property.

**Comment by Mic-M** [comment]
@Apollon77 - Thanks. I have just verified it in the Fritzbox, it is definitely a Fritzbox issue, and **not an adapter issue**. 
I was just able to reproduce the issue with an iPad. It disappears in Fritzbox after a few seconds I turn off WiFi, then it appears again after 10-15 seconds.

@actionbyte - No, I do not use any Mesh APs, just a single Fritzbox.

At this time, my above mentioned workaround script resolved this Fritzbox issue.

**Comment by Apollon77** [comment]
In fact the question from Adapter point of view is if we want to delay the status updates in adapter or have people use custom scripts if interested ... hmm

**Comment by actionbyte** [comment]
Please, can you show me your script when it's ready?

**Comment by Mic-M** [comment]
@Apollon77 - Great question Ingo. I think at this time the adapter is very generic and provides all Fritzbox functionality. Probably a supporting adapter, specifically for presence, by using this TR-064 as basis, would be good as well. So, maintenance can be kept on the core adapter functionality.

@actionbyte - I just published it today :-) See here: [Script](https://github.com/Mic-M/iobroker.presence-script-for-tr-064-community-adapter/blob/master/presence-script-for-tr-064-community-adapter.js)
