### ISSUE TITLE
Sinces some times i can't start tr-64 anymore

### ISSUE THREAD

**Issue by stefanoklett** [iobroker-community-adapters/ioBroker.tr-064-community#56]
This adapter was working well for at least 1 year, and now it dosen't start anymore.
May after some iobroker or adapter update ?

**To Reproduce**  
1. just start the adapter
2. un instances list just play the adapter

  |   |   |  
-- | -- | -- | --
host.linuxsrv01 | 2019-08-08 21:17:08.227 | info | Restart adapter system.adapter.tr-064.0 because enabled
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | instance system.adapter.tr-064.0 terminated with code 1 ()
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: at startup (bootstrap_node.js:160:9)
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: at run (bootstrap_node.js:394:7)
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: at Module.runMain (module.js:611:10)
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: at Function.Module._load (module.js:445:3)
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: at tryModuleLoad (module.js:453:12)
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: at Module.load (module.js:494:32)
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: at Object.Module._extensions..js (module.js:586:10)
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: at Module._compile (module.js:577:32)
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.tr-064/tr-064.js:16:20)
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: at Object.exports.Adapter (/opt/iobroker/node_modules/soef/soef.js:1383:23)
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: TypeError: fns.adapter is not a function
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: ^
host.linuxsrv01 | 2019-08-08 21:17:08.227 | error | Caught by controller[0]: fns.adapter = fns.adapter(options);
host.linuxsrv01 | 2019-08-08 21:17:08.226 | error | Caught by controller[0]: /opt/iobroker/node_modules/soef/soef.js:1383
host.linuxsrv01 | 2019-08-08 21:17:07.865 | info | instance system.adapter.tr-064.0 started with pid 28918

**Expected behavior**  
I expect the adapter will start!

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 3 ~ 1 | 0.4.18
 - JS-Controller version: 1.4.2
 - Node version: v6.16.0
 - Operating system: Linux linuxsrv01 4.9.0-8-686-pae #1 SMP Debian 4.9.144-3.1 (2019-02-19) i686 GNU/Linux

Many tnks for the help
regards
Stefano

**Comment by Apollon77** [comment]
Plese install from this repository!

https://github.com/iobroker-community-adapters/ioBroker.tr-064-community

**Comment by stefanoklett** [comment]
thanks for the tip. but how tho change the repository?
I tried like described here
<https://github.com/iobroker-community-adapters/ioBroker.tr-064-community>,
but the same result
regards

Il giorno gio 8 ago 2019 alle ore 22:12 Ingo Fischer <
notifications@github.com> ha scritto:

**Comment by Apollon77** [comment]
Go into Admin, select the icon with the Github symbol (Custom install), use Custom tab enter the Repo URL from my last post and click install. Then you should get this adapter installed but without instance, klick the "+" in the adapterlist tio create an instance

**Comment by stefanoklett** [comment]
it works fine,
many tnkns
Stefano

Il giorno ven 9 ago 2019 alle ore 15:00 Ingo Fischer <
notifications@github.com> ha scritto:
