### ISSUE TITLE
Phonebook funktioniert nicht

### ISSUE THREAD

**Issue by bahnuhr** [iobroker-community-adapters/ioBroker.tr-064-community#57]
Guten Morgen,
bei der "alten" Version von soef konnte man bei phonebook.number eine Nummer eingeben und es wurde der Name sowie der image.Pfad angegeben (und umgedreht).

Dies funktioniert in der neuen Version nicht mehr. Ich vermute es liegt an der nicht korrekt übernommenen Ordnerstruktur.

soef: tr-064.0.phonebook
community: tr-064-0.states.phonebook

Bitte berichtigen.

**Comment by Apollon77** [comment]
Bitte mit 2.0.0 vom GitHub neu versuchen
