### ISSUE TITLE
...To enable the call monitor dial #96*5* ...

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.tr-064-community#6]
_From @DDDanny on September 22, 2017 19:48_

Dear Team,

log instruction issue - AVM seems to allow to enable this feature only by attached phones (dect / line) - which is from sec. perspective pretty ok.

If you have time, you can add here a text, please:
...To enable the call monitor dial #96*5*... (something like) "from a direct linked phone (dect / line)" - phones connect via the fritz app e.g. cannot grant this...

I'm pretty sure that i granted the last fax via the app... but I got very horny now cauz it didn't worked by using the phone app (via dect phone all was fine then)

Thanks a lot
Danny

_Copied from original issue: soef/ioBroker.tr-064#40_

**Comment by Apollon77** [comment]
Will be Added in 2.0.1
