### ISSUE TITLE
Start nicht möglich: instance system.adapter.tr-064-community.0 terminated with code 1 ()

### ISSUE THREAD

**Issue by matzehard** [iobroker-community-adapters/ioBroker.tr-064-community#61]
Fehler bei Starten des Adapters. IoBroker und der Adapter wurden frisch auf einem RasPi4 installiert.  

![Fehler TR-064](https://user-images.githubusercontent.com/48841831/64488105-fe252600-d243-11e9-9035-e680cd8b22cb.PNG)

Hostname und IP passen. Welcher User auf der Fritzbox verwendet wird (Admin oder User für ioBroker) macht keinen Unterschied.

**Comment by Apollon77** [comment]
In der Fritz of ist alles korrekt eingerichtet und aktiviert? Siehe readme

**Comment by matzehard** [comment]
In readme steht leider nur, was der Adapter alles können sollte. Abgesehen von der Freigabe für Anruflisten (Rufnummer Code) und dem User an der FB anzulegen ist leider nicht viel einzurichten.

**Comment by matzehard** [comment]
Eben nochmal versucht. IoBroker komplett neu installiert, dieses Mal nach Anleitung und nicht per Image. Trotzdem nach wie vor der selbe Fehler. Die Fritzbox meldet keinen Fehler. Nur eine Anmeldung von der IP des Pi4 mit ioBroker. 
- Adminuser und eigens für ioBroker eingerichteter User getestet
- Host fritz.box und IP getestet
- ping vom Pi mit ioBroker funktioniert

**Comment by Apollon77** [comment]
Der User den Du für den Zugriff nutzt muss "FRITZ!Box Einstellungen" aktiviert haben (die oberste der 3 "Rechte"). Hat er das?

**Comment by pinguin21** [comment]
Hatte das gleiche Probem. Mit den Hacken wie oben beschrieben läuft es.
Evt. sollte man das in die Beschreibung des Adapters aufnehmen.

**Comment by pinguin21** [comment]
> Mit den Hacken wie oben beschrieben läuft es.
Mir ist heute aufgefallen, dass der Adapter bei mir doch nicht läuft (wie vor 9 Tagen, siehe oben).
Habe ihn mit Neustart Fritzbox, Adapter, IOBroker bisher nicht zu laufen gekriegt.

**Comment by pinguin21** [comment]
Heute bei mir das Problem gelöst: unter IP hatte ich in der Adapterkonfiguration "fritz.box". Nachdem ich dies auf "192.168.188.1" geändert habe geht es wieder.
