### ISSUE TITLE
Entfernte Fritzbox verbinden

### ISSUE THREAD

**Issue by funboxbolzer** [iobroker-community-adapters/ioBroker.tr-064-community#66]
Hallo.
ist es möglich, eine entfernte Fritzbox einzubinden? Über Myfritz - Adresse? fände ich eine sehr gute Idee.
Gruß Klaus

**Comment by Fishy78** [comment]
Das ist leider per Definition unmöglich, man kann TR-064 nur im eigenen Netz versuchen. Du könntest höchstens versuchen, dich via VPN in die Fritz!Box einzuwählen und dort die lokale Adresse zu verwenden...

**Comment by funboxbolzer** [comment]
Danke dir. Gruß Klaus
