### ISSUE TITLE
datenpunkt falsch deklariert

### ISSUE THREAD

**Issue by liv-in-sky** [iobroker-community-adapters/ioBroker.tr-064-community#71]
durch ein testscript, welches datenpunkte überprüft, bin ich auf folg. fehler aufmerksam geworden
https://forum.iobroker.net/topic/25846/script-info-%C3%BCber-datenpunkte-sammeln?page=1
die meisten davon sind wohl unerheblich - falls das keine problme machen kann, bitte einfach wieder "closen"

![Image 6](https://user-images.githubusercontent.com/18462890/67406262-224f8300-f5b6-11e9-8e72-f93c80155f39.png)

vielleicht wäre es möglich, mir eine tipp zu geben, ob ich noch andere varianten filtern sollte: z.b datenpunkte, die als string deklariert sind und mit number beschrieben wurden - mit der typeof suche kommt da ein fehler - aber eigentlich kann eine nummer auch als string dargestellt werden

**Comment by Apollon77** [comment]
I think in this case all are "false positives" because phonenumbers look like numbers ... but :-) I would leave them more with string because ese zeros at the beginning may be lost or such.
states.ab ist a "Multi type" DP :-(

**Comment by Apollon77** [comment]
But Thank you very much for the issue, I would ignore it in this case
