### ISSUE TITLE
"Reboot" und "ReconnectInternet" Switch triggert auch bei value false

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.tr-064-community#72]
Wenn Objekte boolesch und als Rolle switch sind, dann wäre es logisch dass ihre Funktion nur bei true ausgelöst wird. Dies ist bei folgenden beiden Objekten nicht so. Jede Aktualisierung des Objektes, egal ob true oder false, löst die jeweilige Funktion aus.
```
tr-064-community.0.states.reboot
tr-064-community.0.states.reconnectInternet
```
Ich habe sie nun auf Rolle "Button" umgestellt. So funktioniert es weiterhin und man hat keinen vermeintlich falschen Status.

**Comment by Apollon77** [comment]
will be fixed in 2.0 github later today

**Comment by Diginix** [comment]
Gerne mit type=button statt switch. Wüsste nicht wie man einen Reboot oder Reconnect false schalten kann. Daher ist switch unüblich.

**Comment by Apollon77** [comment]
genau das wird es sein :-)
