### ISSUE TITLE
Adapterkonfiguration: tr-064-community.0  Geräte Liste löschen

### ISSUE THREAD

**Issue by conectas** [iobroker-community-adapters/ioBroker.tr-064-community#76]
Adapterkonfiguration: tr-064-community.0 habe ich eine Geräte Liste angelegt, die lässt sich aber nicht löschen (ging neulich noch).
Exakt: Mann kann die einzelnen Gräte über den Mülleimer einzeln entfernen, werden aber entweder nicht gelöscht oder automatisch wieder angelegt, zumindest ist Sie dann wieder da (reboot /Adapter oder Gerät).

**Comment by Apollon77** [comment]
Please do 2.0.3 when you fixed it.Thank you!

**Comment by Jey-Cee** [comment]
@conectas kannst du mir bitte sagen welche js-controller und admin version du hast? Ich kann den Fehler nicht nachstellen.

**Comment by conectas** [comment]
"_from": "iobroker.js-controller@2.1.1",
  "_id": "iobroker.js-controller@2.1.1",

**Comment by conectas** [comment]
Noch ein Nachtrag:
Wenn ich beim löschen 1 Gerät drin lasse kann, kann ich die anderen Löschen.
Es sieht aus als wenn es nur Probleme gibt wenn ich alle Geräte lösche.

**Comment by Jey-Cee** [comment]
Danke die Letzte Info hat den Hinweis gegeben wo das Problem ist. 
Bitte die neue Version Testen.
