### ISSUE TITLE
Leeres Telefonbuch in FritzBox

### ISSUE THREAD

**Issue by MaKnoNet** [iobroker-community-adapters/ioBroker.tr-064-community#80]
Hallo, wenn in der FritzBox(7490) ein leeres Telefonbuch vorhanden ist kommt es zum Fehler in phonebook.js

 - Adapter version: 2.03
 - JS-Controller version: 2.1.1
 - Node version: v10.18.0
 - Operating system: Raspberry B+, Raspbian GNU/Linux 10 (buster)

![grafik](https://user-images.githubusercontent.com/59054437/71175226-58804a80-2267-11ea-89ff-bfafb3243a1b.png)

**Comment by Apollon77** [comment]
Fixed on GitHub version
