### ISSUE TITLE
lastInactive

### ISSUE THREAD

**Issue by Hans-Zwiesel** [iobroker-community-adapters/ioBroker.tr-064-community#81]
Hallo,
im originalen Adapter gab es das Objekt "lastInactive" ,
Jetzt gibt es nur noch "tr-064-community.0.devices.HUAWEI-P10-Hans.lastActive" - der TimeStamp 
der letzten Anmeldung.
Bevor ich da jetzt ein eigenes Script schreibe - besteht die Möglichkeit, dass von den Entwicklern
ein Objekt mit Timestamp eingefügt wird, womit man die letzte Abmeldung ersehen kann?
Vielen Dank

**Comment by Apollon77** [comment]
Ddr Adapter hat das immer noch, die Objekte werden allerdings erst dann angelegt wenn es das erste mal nötig ist und passiert.

**Comment by Hans-Zwiesel** [comment]
Super - danke!
gut dass ich mit meinem Script noch gewartet habe.
